# Project: RAPGv1
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Core/globals.o Core/input.o Core/main.o Entity/enemy.o Entity/player.o Graphics/render.o Graphics/ui.o Map/map.o
LINKOBJ  = Core/globals.o Core/input.o Core/main.o Entity/enemy.o Entity/player.o Graphics/render.o Graphics/ui.o Map/map.o
LIBS     = -L"C:/Program Files (x86)/GibsTeam/Dev-C++ GTI MOD/Dev-Cpp/Dev-Cpp/MinGW32/lib" -L"C:/Program Files (x86)/GibsTeam/Dev-C++ GTI MOD/Dev-Cpp/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -mwindows -lglut32 -lglu32 -lopengl32 -lwinmm -lgdi32 -g3
INCS     = -I"C:/Program Files (x86)/GibsTeam/Dev-C++ GTI MOD/Dev-Cpp/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/GibsTeam/Dev-C++ GTI MOD/Dev-Cpp/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Program Files (x86)/GibsTeam/Dev-C++ GTI MOD/Dev-Cpp/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"C:/Program Files (x86)/GibsTeam/Dev-C++ GTI MOD/Dev-Cpp/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/GibsTeam/Dev-C++ GTI MOD/Dev-Cpp/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Program Files (x86)/GibsTeam/Dev-C++ GTI MOD/Dev-Cpp/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/Program Files (x86)/GibsTeam/Dev-C++ GTI MOD/Dev-Cpp/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = RAPGv1.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3 -DGLUT_STATIC
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Core/globals.o: Core/globals.cpp
	$(CPP) -c Core/globals.cpp -o Core/globals.o $(CXXFLAGS)

Core/input.o: Core/input.cpp
	$(CPP) -c Core/input.cpp -o Core/input.o $(CXXFLAGS)

Core/main.o: Core/main.cpp
	$(CPP) -c Core/main.cpp -o Core/main.o $(CXXFLAGS)

Entity/enemy.o: Entity/enemy.cpp
	$(CPP) -c Entity/enemy.cpp -o Entity/enemy.o $(CXXFLAGS)

Entity/player.o: Entity/player.cpp
	$(CPP) -c Entity/player.cpp -o Entity/player.o $(CXXFLAGS)

Graphics/render.o: Graphics/render.cpp
	$(CPP) -c Graphics/render.cpp -o Graphics/render.o $(CXXFLAGS)

Graphics/ui.o: Graphics/ui.cpp
	$(CPP) -c Graphics/ui.cpp -o Graphics/ui.o $(CXXFLAGS)

Map/map.o: Map/map.cpp
	$(CPP) -c Map/map.cpp -o Map/map.o $(CXXFLAGS)
